### PR TITLE
ENH: package the tests so downstream extensions can use them

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by mrocklin** [comment]
Looks good to me.  Thanks @CJ-Wright 

The test is unrelated.  Dask master has breaking changes.  We should probably change tests to work with latest release.

**Comment by mrocklin** [comment]
Whoops, my apologies.  It looks like we had a race condition.

**Comment by CJ-Wright** [comment]
Sorry I'll put in another PR.

**Comment by mrocklin** [comment]
Don't be sorry.  It's entirely my fault.  I shouldn't have been trigger
happy :)

**Pull request merged**
