### PR TITLE
ENH: Add Stream classes that expect DataFrames.

### PR DESCRIPTION
**Pull request by danielballan**
This is a modest start at integrating DataFrames with streams, as suggested in the blog post. Example:

```python
In [54]: source = Stream()

In [55]: df = pd.DataFrame({'a': [1,2,3], 'b': [2,3,4]})

In [56]: import streams.dataframe as sd

In [57]: sd.max(source).map(print)
Out[57]: <streams.core.map at 0x111f20940>

In [58]: source.emit(df)
a    3.0
b    4.0
dtype: float64
Out[58]: []

In [59]: source.emit(df)
a    3.0
b    4.0
dtype: float64
Out[59]: []

In [60]: source.emit(df * 2)
a    6.0
b    8.0
dtype: float64
Out[60]: []
```

### CODE REVIEW

**Comment by mrocklin** [comment]
This may be an alternative: https://github.com/mrocklin/pandas-streaming

**Comment by danielballan** [comment]
Interesting. What you've done with the `example` attribute is a good idea.

**Comment by mrocklin** [comment]
Stolen from dask.dataframe, which does the same thing.

**Comment by jrmlhermitte** [comment]
Great start :-)
I think this has been superseded with #73 .

**Comment by danielballan** [comment]
Indeed!

**Pull request closed without merging**
