### PR TITLE
Dataframes

### PR DESCRIPTION
**Pull request by snth**
Adds the Streaming Dataframes plot example from your blog.

Btw, I find it a bit confusing/unclear where the output ends up. In particular in my case it tends to go to the cell where the last code execution was. 

So I couldn't get it to look nice like your gifs and rather my output ended up all going to the same cell. Having multiple commands' output appear in the same cell produced a lot of flicker for me. That is why I have the earlier output producing commands commented out.

### CODE REVIEW

**Comment by mrocklin** [comment]
> Btw, I find it a bit confusing/unclear where the output ends up. In particular in my case it tends to go to the cell where the last code execution was.

Interesting.  Can I ask you to try updating `ipywidgets` and see if things change for you?

**Comment by snth** [comment]
Just tried that. 

    ipywidgets: 6.0.0-py36_0 --> 7.0.1-py_2 conda-forge

That didn't change anything.

Trying `conda update --all -c conda-forge` next.

**Comment by snth** [comment]
Ok, it's working now. Not sure what did it.

I had restarted the kernel after the `ipywidgets` update but hadn't restarted the jupyter notebook server.

This is so awesome!

**Comment by mrocklin** [comment]
Merging.  Thanks @snth !

**Pull request merged**
