### PR TITLE
Example of using streamz with asyncio to use the timed_window() method #95

### PR DESCRIPTION
**Pull request by snth**
This actually turned out to be pretty easy.

The main thing to watch out for that I noticed is that the 

    AsyncIOMainLoop().install()

call has to occurr before the Stream() is created.

### CODE REVIEW

**Comment by mrocklin** [comment]
This looks great.  Thank you for putting this together @snth .  Merging

**Comment by mrocklin** [comment]
Were you able to get your system up and running then?

**Comment by snth** [comment]
@mrocklin Yes, it works great now! 

I didn't get to say this earlier but thank you for creating `streamz`. I'm loving it so far!

I think `numismatic` will be a good showcase of where the Streams functionality really simplifies the design. We're still sorting out some basics and putting in more functionality but I'll ping you once I think it's worth trying out.

**Comment by mrocklin** [comment]
> I didn't get to say this earlier but thank you for creating streamz. I'm loving it so far!

I'm glad.  I encourage you to speak up in the future.  Early users are helpful in determining the direction of a project.

> I think numismatic will be a good showcase of where the Streams functionality really simplifies the design. We're still sorting out some basics and putting in more functionality but I'll ping you once I think it's worth trying out.

I look forward to it

**Pull request merged**
