### PR TITLE
ENH: support dicts in unique

### LINKED ISSUE #140: unique fails on dicts
```python
from streamz import Stream
source = Stream()
s = source.unique().sink(print)
source.emit({'a': 1})
```
gives an error
```
~/dev/streamz/streamz/core.py in emit(self, x, asynchronous)
    243                 thread_state.asynchronous = True
    244             try:
--> 245                 result = self._emit(x)
    246                 return gen.convert_yielded(result)
    247             finally:

~/dev/streamz/streamz/core.py in _emit(self, x)
    224         result = []
    225         for downstream in list(self.downstreams):
--> 226             r = downstream.update(x, who=self)
    227             if type(r) is list:
    228                 result.extend(r)

~/dev/streamz/streamz/core.py in update(self, x, who)
    992     def update(self, x, who=None):
    993         y = self.key(x)
--> 994         if y not in self.seen:
    995             self.seen[y] = 1
    996             return self._emit(x)

TypeError: unhashable type: 'dict'
```
Is this expected behavior?

### PR DESCRIPTION
**Pull request by CJ-Wright**
Closes #140

### CODE REVIEW

**Comment by mrocklin** [comment]
FYI I am unlikely to review this in the next week or so.

**Comment by CJ-Wright** [comment]
I'd really like this to get in before the 16th (we're deploying at the NSLS) do you want me to just merge, seek review from someone else or something else entirely. I'd rather not just work from my fork since I'd like to give the NSLS a stable release (but I can do that too if needed).

**Comment by mrocklin** [comment]
I'm -1 on these changes.  This seems too special cased to me.  What about other non-dicts that are not hashable?

I recommend doing what toolz.unique does and accept a key function.

**Comment by mrocklin** [comment]
> I'd really like this to get in before the 16th (we're deploying at the NSLS) do you want me to just merge, seek review from someone else or something else entirely. I'd rather not just work from my fork since I'd like to give the NSLS a stable release (but I can do that too if needed).

This seems unsustainable to me.  I think that you need to develop a long term solution that does not require my short-term involvement.  I am not comfortable with others just-merging into this fork.  I recommend forking the project for your needs or developing your own Stream objects in an auxiliary library.  If there is anything I can do to help improve extensibility so that coordination is not as important please let me know.

**Comment by CJ-Wright** [comment]
I guess my best bet then is to build an extension library that adds functionality.

**Comment by mrocklin** [comment]
> I guess my best bet then is to build an extension library that adds functionality.

I agree that this would probably reduce friction and allow you to develop and release according to your own needs.

**Comment by mrocklin** [comment]
It looks like there already is a key= keyword to unique.  Perhaps that
solves your immediate problem.

**Comment by CJ-Wright** [comment]
I guess I don't understand how that is supposed to work, do I then try to hash (or something similar) the dict in the `key` function?

**Comment by mrocklin** [comment]
http://toolz.readthedocs.io/en/latest/api.html#toolz.itertoolz.unique  The
key is up to you

**Pull request closed without merging**
