### PR TITLE
I'll try that one again

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Either way works for me. Do you want me to make the modification?

**Comment by mrocklin** [comment]
Yes.  That way we'll get tests for streamz.dataframe as well and future
modules won't need to update this list.

**Comment by CJ-Wright** [comment]
@mrocklin I think this may be ready to go?

**Comment by mrocklin** [comment]
Grand.  Thanks @CJ-Wright !  Sorry again for my snafu!

**Comment by CJ-Wright** [comment]
Thank you!

**Pull request merged**
